version: '3.9'
services:
  work:
    restart: always
    build:
      context: .
      args:
        - NODE_VERSION=${NODE_VERSION}
        - NPM_VERSION=${NPM_VERSION}
        - PYTHON_VERSION=${PYTHON_VERSION}
        - RUST_VERSION=${RUST_VERSION}
    container_name: 'work_container'
    tty: true
    volumes:
      - ~/.aws:/root/.aws
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
      - /usr/local/lib/docker:/usr/local/lib/docker
      - .:/workspace
      - ~:/root/host
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    privileged: true
